function out1 = A_cut(A,alpha,r,y)
%A_CUT
%    OUT1 = A_CUT(A,ALPHA,R,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    03-Dec-2018 15:21:32

out1 = -(alpha.*(A+y).*(r+1.0))./(-alpha+r+1.0);
