function out1 = As(p,yh,yl)
%AS
%    OUT1 = AS(P,YH,YL)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    14-Nov-2018 11:44:11

t2 = yl.^2;
t3 = yh.^2;
t4 = p+2.0;
t5 = 1.0./t4;
t6 = yh.*5.0;
t7 = p.^2;
t8 = t2.*t7;
t9 = yh.*yl.*6.0;
t10 = p.*t2.*2.0;
t11 = t3.*9.0;
t12 = t2+t8+t9+t10+t11-p.*t3.*8.0-p.*yh.*yl.*2.0;
t13 = sqrt(t12);
out1 = [(t5.*(t6+t13-yl-p.*yl))./2.0;t5.*(-t6+t13+yl+p.*yl).*(-1.0./2.0)];
