function out1 = A_cut3(A,alpha,m,r,y)
%A_CUT3
%    OUT1 = A_CUT3(A,ALPHA,M,R,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    08-Dec-2018 13:24:56

out1 = -(alpha.*m.*(A+y).*(r+1.0))./(r-alpha.*m+1.0);
