function out1 = A_cut3_con(A,alpha,m,p1,p2,y)
%A_CUT3_CON
%    OUT1 = A_CUT3_CON(A,ALPHA,M,P1,P2,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    11-Dec-2018 16:23:51

t2 = p1.^2;
t3 = alpha.^2;
t4 = 1.0./p2;
t5 = alpha-2.0;
t6 = 1.0./t5;
t7 = alpha.*m;
t8 = alpha+t7-2.0;
t9 = A.*alpha.*p2.*8.0;
t10 = alpha.*p2.*y.*8.0;
t11 = m.^2;
t12 = t2.*t3.*t11;
t13 = t2+t9+t10+t12-A.*p2.*t3.*4.0-alpha.*m.*t2.*2.0-p2.*t3.*y.*4.0-m.*p2.*t3.*y.*4.0-A.*m.*p2.*t3.*4.0;
t14 = sqrt(t13);
out1 = (m.*t4.*t6.*(t2-alpha.*t2-A.*alpha.*p2.*4.0+A.*p2.*t3.*2.0-alpha.*p2.*y.*4.0+p2.*t3.*y.*2.0))./(t8.*2.0)-(m.*p1.*t4.*t6.*1.0./t8.^2.*(alpha-1.0).*(t14.*2.0-alpha.*t14+alpha.*m.*p1-m.*p1.*t3))./2.0;
