function out1 = A_cut2_1_con(A,alpha,p1,p2,r,w,y)
%A_CUT2_1_CON
%    OUT1 = A_CUT2_1_CON(A,ALPHA,P1,P2,R,W,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    11-Dec-2018 13:19:48

t2 = p1.^2;
t3 = alpha.^2;
t4 = r.^2;
t5 = 1.0./p2;
t6 = p2.*w;
t7 = p1+t6;
t8 = alpha-2.0;
t9 = 1.0./t8;
t10 = r+1.0;
t11 = 1.0./t10;
t12 = p1.*r;
t13 = t2.*t4;
t14 = r.*t2.*2.0;
t15 = t2.*t3.*4.0;
t16 = A.*alpha.*p2.*8.0;
t17 = alpha.*p2.*y.*8.0;
t18 = p2.^2;
t19 = w.^2;
t20 = t3.*t18.*t19.*4.0;
t21 = alpha.*p2.*r.*y.*1.6e1;
t22 = A.*alpha.*p2.*t4.*8.0;
t23 = p1.*p2.*t3.*w.*8.0;
t24 = alpha.*p2.*t4.*y.*8.0;
t25 = A.*alpha.*p2.*r.*1.6e1;
t26 = t2+t13+t14+t15+t16+t17+t20+t21+t22+t23+t24+t25-alpha.*t2.*4.0-A.*p2.*t3.*4.0-alpha.*r.*t2.*4.0-p2.*t3.*y.*4.0-alpha.*p1.*p2.*w.*4.0-p2.*r.*t3.*y.*8.0-p2.*t3.*t4.*y.*4.0-A.*p2.*r.*t3.*8.0-A.*p2.*t3.*t4.*4.0-alpha.*p1.*p2.*r.*w.*4.0;
t27 = sqrt(t26);
out1 = [-t5.*t7.*t9.*t11.*(p1+t12+t27-alpha.*p1.*2.0-alpha.*p2.*w.*2.0);t5.*t7.*t9.*t11.*(-p1-t12+t27+alpha.*p1.*2.0+alpha.*p2.*w.*2.0)];
