function out1 = cut_dklc(alpha,k,p1,y)
%CUT_DKLC
%    OUT1 = CUT_DKLC(ALPHA,K,P1,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    12-Sep-2019 10:08:37

out1 = y+k.*p1+y./(alpha-1.0);
