function out1 = cut_quad(alpha,p1,p2)
%CUT_QUAD
%    OUT1 = CUT_QUAD(ALPHA,P1,P2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    13-Feb-2020 14:34:01

out1 = -1.0./(p2.*2.0+1.0).^2.*(alpha-p1).*(p1+alpha.*p2+p1.*p2);
