function out1 = cut_ql(alpha,p1,p2)
%CUT_QL
%    OUT1 = CUT_QL(ALPHA,P1,P2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    05-Feb-2020 10:35:13

t2 = p1.^2;
out1 = alpha.*(-1.0./2.0)+(t2./8.0-(p1.*sqrt(t2+alpha.*p2.*8.0))./8.0)./p2;
