function out1 = cut_ql(alpha,k,p1)
%CUT_QL
%    OUT1 = CUT_QL(ALPHA,K,P1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    11-Sep-2019 21:26:11

out1 = -p1.*(k-alpha.*p1);
