function out1 = cut_d(alpha,p1,p2,y)
%CUT_D
%    OUT1 = CUT_D(ALPHA,P1,P2,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    12-Dec-2018 11:52:35

t2 = p1.^2;
out1 = (t2./8.0+(p2.*y)./2.0-(p1.*1.0./sqrt(-alpha+1.0).*sqrt(t2-alpha.*t2+alpha.*p2.*y.*8.0))./8.0)./p2+y./(alpha.*2.0-2.0);
