function out1 = v_b_dk(L,alpha,k,p1,p2,y)
%V_B_DK
%    OUT1 = V_B_DK(L,ALPHA,K,P1,P2,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    14-Dec-2018 10:46:22

out1 = -log(y).*(alpha-1.0)+alpha.*log(k-(p1-sqrt(L.*p2.*-4.0+p1.^2))./(p2.*2.0));
