function out1 = v_b_dkc(L,alpha,k,p1,p2,y)
%V_B_DKC
%    OUT1 = V_B_DKC(L,ALPHA,K,P1,P2,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    13-Sep-2019 09:06:04

out1 = y.^(-alpha+1.0).*(k-(p1-sqrt(L.*p2.*-4.0+p1.^2))./(p2.*2.0)).^alpha;
