function out1 = v_b_quad(L,alpha,p1,p2,y)
%V_B_QUAD
%    OUT1 = V_B_QUAD(L,ALPHA,P1,P2,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    13-Feb-2020 14:34:02

t2 = alpha+(p1-sqrt(L.*p2.*-4.0+p1.^2))./(p2.*2.0);
out1 = y-t2.^2./2.0;
