function vse = v_b_con(A,Ap,alpha,m,p1,p2,rh,y)
%V_B_CON
%    VSE = V_B_CON(A,AP,ALPHA,M,P1,P2,RH,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    11-Dec-2018 16:23:28

t2 = 1.0./p2;
t3 = alpha-2.0;
t4 = 1.0./t3;
t5 = alpha.^2;
t6 = alpha-1.0;
t7 = 1.0./t3.^2;
t8 = rh+1.0;
t9 = 1.0./t8;
t10 = p1.^2;
t11 = m.*t10;
t12 = A.*alpha.*p2.*8.0;
t13 = alpha.*p2.*y.*8.0;
t14 = Ap.*p2.*t5.*4.0;
t15 = alpha.*p2.*rh.*y.*8.0;
t16 = A.*alpha.*p2.*rh.*8.0;
t17 = t11+t12+t13+t14+t15+t16-Ap.*alpha.*p2.*8.0-A.*p2.*t5.*4.0-p2.*t5.*y.*4.0-p2.*rh.*t5.*y.*4.0-A.*p2.*rh.*t5.*4.0;
t18 = sqrt(t17);
vse = -t6.*log(t6.*t7.*t9.*(A.*8.0-Ap.*8.0+y.*8.0-A.*alpha.*4.0+Ap.*alpha.*4.0+A.*rh.*8.0-alpha.*y.*4.0+rh.*y.*8.0-A.*alpha.*rh.*4.0-alpha.*rh.*y.*4.0).*(-1.0./2.0)-(t2.*t6.*t7.*t9.*(t11-sqrt(m).*p1.*t18))./2.0)+alpha.*log((p1.*t2.*t4)./2.0-(1.0./sqrt(m).*t2.*t4.*t18)./2.0);
