function out1 = v_b_ql(L,alpha,p1,p2,y)
%V_B_QL
%    OUT1 = V_B_QL(L,ALPHA,P1,P2,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    05-Feb-2020 10:35:14

out1 = y-alpha.*(-log(-p1+sqrt(L.*p2.*-4.0+p1.^2))+log(2.0)+log(p2));
