function out1 = v_b_d(L,alpha,p1,p2,y)
%V_B_D
%    OUT1 = V_B_D(L,ALPHA,P1,P2,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    12-Dec-2018 11:52:36

out1 = -log(y).*(alpha-1.0)+alpha.*log(((p1-sqrt(L.*p2.*-4.0+p1.^2)).*(-1.0./2.0))./p2);
