function out1 = v_b_ql(L,alpha,k,p1,y)
%V_B_QL
%    OUT1 = V_B_QL(L,ALPHA,K,P1,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    11-Sep-2019 21:26:12

t2 = k+L./p1;
out1 = y-t2.^2./(alpha.*2.0);
