function out1 = v_b_dklc(L,alpha,k,p1,y)
%V_B_DKLC
%    OUT1 = V_B_DKLC(L,ALPHA,K,P1,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    12-Sep-2019 10:08:37

out1 = y.^(-alpha+1.0).*(k-L./p1).^alpha;
