function out1 = v_b_dkl(L,alpha,k,p1,y)
%V_B_DKL
%    OUT1 = V_B_DKL(L,ALPHA,K,P1,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    13-May-2019 13:54:27

out1 = -log(y).*(alpha-1.0)+alpha.*log(k-L./p1);
