function vse = v_reg_dkc(L,alpha,k,p1,p2,y)
%V_REG_DKC
%    VSE = V_REG_DKC(L,ALPHA,K,P1,P2,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    13-Sep-2019 09:06:02

t2 = k.^2;
t3 = p2.^2;
t4 = alpha.^2;
t5 = alpha-2.0;
t6 = 1.0./t5;
t7 = 1.0./p2;
t8 = p1.^2;
t9 = t2.*t3.*4.0;
t10 = alpha.*p2.*y.*8.0;
t11 = t2.*t3.*t4.*4.0;
t12 = L.*p2.*t4.*4.0;
t13 = alpha.*k.*p1.*p2.*8.0;
t18 = p2.*t4.*y.*4.0;
t19 = alpha.*t2.*t3.*8.0;
t20 = L.*alpha.*p2.*8.0;
t21 = k.*p1.*p2.*4.0;
t22 = k.*p1.*p2.*t4.*4.0;
t14 = t8+t9+t10+t11+t12+t13-t18-t19-t20-t21-t22;
t15 = sqrt(t14);
t17 = k.*p2.*2.0;
t23 = alpha.*k.*p2.*2.0;
t16 = p1-t15+t17-t23;
vse = (k+t6.*(k-alpha.*k)+t6.*t7.*(p1./2.0-t15./2.0)).^alpha.*(-L+y-(1.0./t5.^2.*t7.*t16.^2)./4.0-(p1.*t6.*t7.*t16)./2.0).^(-alpha+1.0);
