function vse = v_reg_con(A,Ap,alpha,p1,p2,r,y)
%V_REG_CON
%    VSE = V_REG_CON(A,AP,ALPHA,P1,P2,R,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    11-Dec-2018 16:44:49

t2 = r.^2;
t3 = alpha-1.0;
t4 = alpha-2.0;
t5 = 1.0./t4.^2;
t6 = r+1.0;
t7 = 1.0./t6.^2;
t8 = p1.^2;
t9 = alpha.^2;
t10 = 1.0./p2;
t11 = 1.0./t4;
t12 = r.*t8;
t13 = A.*alpha.*p2.*8.0;
t14 = alpha.*p2.*y.*8.0;
t15 = Ap.*p2.*t9.*4.0;
t16 = alpha.*p2.*r.*y.*8.0;
t17 = A.*alpha.*p2.*r.*8.0;
t18 = t8+t12+t13+t14+t15+t16+t17-Ap.*alpha.*p2.*8.0-A.*p2.*t9.*4.0-p2.*t9.*y.*4.0-p2.*r.*t9.*y.*4.0-A.*p2.*r.*t9.*4.0;
t19 = sqrt(t18);
vse = -t3.*log(t3.*t5.*t7.*(A.*8.0-Ap.*8.0+y.*8.0-A.*alpha.*4.0+Ap.*alpha.*4.0+A.*r.*1.6e1-Ap.*r.*8.0+A.*t2.*8.0-alpha.*y.*4.0+r.*y.*1.6e1+t2.*y.*8.0-A.*alpha.*r.*8.0+Ap.*alpha.*r.*4.0-A.*alpha.*t2.*4.0-alpha.*r.*y.*8.0-alpha.*t2.*y.*4.0).*(-1.0./2.0)-(t3.*t5.*t7.*t10.*(t8+r.*t8.*2.0+t2.*t8-p1.*t6.^(3.0./2.0).*t19))./2.0)+alpha.*log((p1.*t10.*t11)./2.0-(1.0./sqrt(t6).*t10.*t11.*t19)./2.0);
