function vse = v_reg_ql(L,alpha,k,p1,p2,y)
%V_REG_QL
%    VSE = V_REG_QL(L,ALPHA,K,P1,P2,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    05-Feb-2020 10:35:12

t2 = p1.^2;
t3 = 1.0./p2;
t4 = alpha.*p2.*8.0;
t5 = t2+t4;
t6 = sqrt(t5);
t7 = k+(t3.*(p1-t6))./4.0;
vse = -L-alpha./2.0+y+t3.*(t2./8.0-(p1.*t6)./8.0)-t7.^2./(alpha.*2.0);
