function vse = v_reg_dkl(L,alpha,k,p1,y)
%V_REG_DKL
%    VSE = V_REG_DKL(L,ALPHA,K,P1,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    13-May-2019 13:54:26

t2 = alpha-1.0;
vse = alpha.*log(alpha.*k-(L.*alpha-alpha.*y)./p1)-t2.*log(-t2.*(-L+y+k.*p1));
