function vse = v_reg_dklc(L,alpha,k,p1,y)
%V_REG_DKLC
%    VSE = V_REG_DKLC(L,ALPHA,K,P1,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    12-Sep-2019 10:08:36

vse = (alpha.*k-(L.*alpha-alpha.*y)./p1).^alpha.*(-(alpha-1.0).*(-L+y+k.*p1)).^(-alpha+1.0);
