function vse = v_reg_ql(L,alpha,p1,p2,y)
%V_REG_QL
%    VSE = V_REG_QL(L,ALPHA,P1,P2,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    05-Feb-2020 14:56:54

t2 = 1.0./p2;
t3 = alpha.*p2.*8.0;
t4 = p1.^2;
t5 = t3+t4;
t6 = sqrt(t5);
vse = -L-alpha./2.0+y+t2.*(t4./8.0-(p1.*t6)./8.0)+alpha.*log(t2.*(p1-t6).*(-1.0./4.0));
