function vse = v_reg_quad(L,alpha,p1,p2,y)
%V_REG_QUAD
%    VSE = V_REG_QUAD(L,ALPHA,P1,P2,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    13-Feb-2020 14:34:01

t3 = p2.*2.0;
t4 = t3+1.0;
t2 = alpha-(alpha-p1)./t4;
t5 = p1.^2;
vse = -L+y-t2.^2./2.0+1.0./t4.^2.*(t5-alpha.*p1+p2.*(t5-alpha.^2));
