function out1 = v_reg(A,Ap,alpha,p,r,y)
%V_REG
%    OUT1 = V_REG(A,AP,ALPHA,P,R,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    08-Dec-2018 13:23:19

t2 = r+1.0;
t3 = A.*r;
t4 = r.*y;
t5 = A-Ap+t3+t4+y;
t6 = log(t2);
t7 = log(t5);
t8 = -alpha+1.0;
t9 = log(t8);
out1 = -t6+t7+t9+alpha.*log((alpha.*t5)./(p.*t2))-alpha.*(-t6+t7+t9);
