function vse = v_reg_ql(L,alpha,k,p1,y)
%V_REG_QL
%    VSE = V_REG_QL(L,ALPHA,K,P1,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    11-Sep-2019 21:26:11

vse = -L+y-k.*p1+(alpha.*p1.^2)./2.0;
