function vse = v_reg_d(L,alpha,p1,p2,y)
%V_REG_D
%    VSE = V_REG_D(L,ALPHA,P1,P2,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    12-Dec-2018 11:52:33

% alpha=.02;
% p1=15;
% p2=0.001;
% L=0;
% y=20000;

t2 = alpha.^2;
t3 = alpha-2.0;
t4 = 1.0./p2;
t5 = alpha-1.0;
t6 = 1.0./t3.^2;
t7 = p1.^2;
t8 = alpha.*p2.*y.*8.0;
t9 = L.*p2.*t2.*4.0;
t10 = t7+t8+t9-L.*alpha.*p2.*8.0-p2.*t2.*y.*4.0;
t11 = sqrt(t10);
vse = alpha.*log((t4.*(p1-t11))./(t3.*2.0))-t5.*log((t5.*t6.*(L.*8.0-y.*8.0-L.*alpha.*4.0+alpha.*y.*4.0))./2.0-(t4.*t5.*t6.*(t7-p1.*t11))./2.0);
