function out1 = w_b(A,Ap,alpha,p,rh,rl,y)
%W_B
%    OUT1 = W_B(A,AP,ALPHA,P,RH,RL,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    08-Dec-2018 13:23:10

out1 = (alpha.*(rl+1.0).*(A-Ap+y+A.*rh+rh.*y))./(p.*(rl+rh.*rl+1.0));
