function out1 = w_b_ql(L,p1,p2)
%W_B_QL
%    OUT1 = W_B_QL(L,P1,P2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    05-Feb-2020 10:35:13

out1 = ((p1-sqrt(L.*p2.*-4.0+p1.^2)).*(-1.0./2.0))./p2;
