function out1 = w_b_dkc(L,p1,p2)
%W_B_DKC
%    OUT1 = W_B_DKC(L,P1,P2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    13-Sep-2019 09:06:04

out1 = ((p1-sqrt(L.*p2.*-4.0+p1.^2)).*(-1.0./2.0))./p2;
