function wse = w_b_con(A,Ap,alpha,m,p1,p2,rh,y)
%W_B_CON
%    WSE = W_B_CON(A,AP,ALPHA,M,P1,P2,RH,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    11-Dec-2018 16:23:28

t2 = 1.0./p2;
t3 = alpha-2.0;
t4 = 1.0./t3;
t5 = alpha.^2;
wse = (p1.*t2.*t4)./2.0-(1.0./sqrt(m).*t2.*t4.*sqrt(m.*p1.^2+A.*alpha.*p2.*8.0-Ap.*alpha.*p2.*8.0-A.*p2.*t5.*4.0+Ap.*p2.*t5.*4.0+alpha.*p2.*y.*8.0-p2.*t5.*y.*4.0+alpha.*p2.*rh.*y.*8.0-p2.*rh.*t5.*y.*4.0+A.*alpha.*p2.*rh.*8.0-A.*p2.*rh.*t5.*4.0))./2.0;
