function out1 = w_b_dk(L,p1,p2)
%W_B_DK
%    OUT1 = W_B_DK(L,P1,P2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    14-Dec-2018 10:46:22

out1 = ((p1-sqrt(L.*p2.*-4.0+p1.^2)).*(-1.0./2.0))./p2;
