function out1 = w_b_quad(L,p1,p2)
%W_B_QUAD
%    OUT1 = W_B_QUAD(L,P1,P2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    13-Feb-2020 14:34:01

out1 = ((p1-sqrt(L.*p2.*-4.0+p1.^2)).*(-1.0./2.0))./p2;
