function wse = w_reg_quad(alpha,p1,p2)
%W_REG_QUAD
%    WSE = W_REG_QUAD(ALPHA,P1,P2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    13-Feb-2020 14:34:00

wse = (alpha-p1)./(p2.*2.0+1.0);
