function wse = w_reg_dk(L,alpha,k,p1,p2,y)
%W_REG_DK
%    WSE = W_REG_DK(L,ALPHA,K,P1,P2,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    15-Dec-2018 17:56:09

t2 = k.^2;
t3 = p2.^2;
t4 = alpha.^2;
t5 = alpha-2.0;
t6 = 1.0./t5;
wse = t6.*(k-alpha.*k)+(t6.*(p1./2.0-sqrt(t2.*t3.*4.0+p1.^2-L.*alpha.*p2.*8.0+L.*p2.*t4.*4.0-alpha.*t2.*t3.*8.0+alpha.*p2.*y.*8.0-k.*p1.*p2.*4.0+t2.*t3.*t4.*4.0-p2.*t4.*y.*4.0+alpha.*k.*p1.*p2.*8.0-k.*p1.*p2.*t4.*4.0)./2.0))./p2;
