function wse = w_reg_d(L,alpha,p1,p2,y)
%W_REG_D
%    WSE = W_REG_D(L,ALPHA,P1,P2,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    12-Dec-2018 11:52:33

t2 = alpha.^2;
wse = (p1-sqrt(p1.^2-L.*alpha.*p2.*8.0+L.*p2.*t2.*4.0+alpha.*p2.*y.*8.0-p2.*t2.*y.*4.0))./(p2.*(alpha-2.0).*2.0);
