function wse = w_reg_dklc(L,alpha,k,p1,y)
%W_REG_DKLC
%    WSE = W_REG_DKLC(L,ALPHA,K,P1,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    12-Sep-2019 10:08:36

wse = -k+alpha.*k-(L.*alpha-alpha.*y)./p1;
