function wse = w_reg_ql(alpha,p1,p2)
%W_REG_QL
%    WSE = W_REG_QL(ALPHA,P1,P2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    05-Feb-2020 14:55:39

wse = ((p1-sqrt(alpha.*p2.*8.0+p1.^2)).*(-1.0./4.0))./p2;
