function wse = w_reg_ql(alpha,k,p1)
%W_REG_QL
%    WSE = W_REG_QL(ALPHA,K,P1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    11-Sep-2019 21:26:11

wse = k-alpha.*p1;
