function wse = w_reg_con(A,Ap,alpha,p1,p2,r,y)
%W_REG_CON
%    WSE = W_REG_CON(A,AP,ALPHA,P1,P2,R,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    11-Dec-2018 16:44:48

t2 = 1.0./p2;
t3 = alpha-2.0;
t4 = 1.0./t3;
t5 = p1.^2;
t6 = alpha.^2;
wse = (p1.*t2.*t4)./2.0-(t2.*t4.*1.0./sqrt(r+1.0).*sqrt(t5+r.*t5+A.*alpha.*p2.*8.0-Ap.*alpha.*p2.*8.0-A.*p2.*t6.*4.0+Ap.*p2.*t6.*4.0+alpha.*p2.*y.*8.0-p2.*t6.*y.*4.0+alpha.*p2.*r.*y.*8.0-p2.*r.*t6.*y.*4.0+A.*alpha.*p2.*r.*8.0-A.*p2.*r.*t6.*4.0))./2.0;
