function out1 = w_reg(A,Ap,alpha,p,r,y)
%W_REG
%    OUT1 = W_REG(A,AP,ALPHA,P,R,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    08-Dec-2018 13:23:18

out1 = (alpha.*(A-Ap+y+A.*r+r.*y))./(p.*(r+1.0));
