function X = Xprep(Atoday,Btoday,Dtoday)

X = [        ...
            Atoday Atoday.*Atoday Atoday.*Atoday.*Atoday ...
            Atoday.*Dtoday Atoday.*Atoday.*Dtoday Atoday.*Atoday.*Atoday.*Dtoday ...
            Btoday Btoday.*Btoday Btoday.*Btoday.*Btoday ...
            Btoday.*Dtoday Btoday.*Btoday.*Dtoday Btoday.*Btoday.*Btoday.*Dtoday ...
            Btoday.*Atoday Btoday.*Btoday.*Atoday Btoday.*Atoday.*Atoday ...
            ];