function out1 = A_cut2_1(A,alpha,r,y)
%A_CUT2_1
%    OUT1 = A_CUT2_1(A,ALPHA,R,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    03-Dec-2018 15:21:32

out1 = (alpha.*(A+y).*(r+1.0).*-2.0)./(alpha.*-2.0+r+1.0);
