function out1 = v_b(A,Ap,alpha,p,rh,rl,y)
%V_B
%    OUT1 = V_B(A,AP,ALPHA,P,RH,RL,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    03-Dec-2018 15:21:28

t2 = -alpha+1.0;
t3 = log(t2);
t4 = rh+1.0;
t5 = log(t4);
out1 = t3-t5+log(A-Ap+y+A.*rh+rh.*y)-alpha.*t3+alpha.*t5-alpha.*log(rl+rh.*rl+1.0)+alpha.*log(alpha)-alpha.*log(p)+alpha.*log(rl+1.0);
