function out1 = v_b2(A,Ab,Ap,alpha,p,rh,rl,y)
%V_B2
%    OUT1 = V_B2(A,AB,AP,ALPHA,P,RH,RL,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    03-Dec-2018 15:21:30

t2 = A.*rh;
t3 = A.*rl;
t4 = rh.*y;
t5 = rl.*y;
t6 = A.*rh.*rl;
t7 = rh.*rl.*y;
t8 = A-Ap+t2+t3+t4+t5+t6+t7+y-Ab.*rh-Ap.*rl;
t9 = alpha-1.0;
out1 = alpha.*log((alpha.*t8)./(p.*(rl+rh.*rl+1.0)))-t9.*log(-(t8.*t9)./((rh+1.0).*(rl+1.0)));
